### ISSUE TITLE
Support for .jsbeatifyrc in cli? Am I missing something? 

### ISSUE THREAD

**Issue by mseashor** [teazean/vue-beautify#1]
This project is awesome!  I can see that it's new, but it comes close to helping me out with what I need to do to promote Vue.js within my company.  The first step would be getting our existing .jsbeatifyrc to work with .vue files.  I don't think this works in the cli code right now unless I'm missing something.

Background: I'm working to get Vue.js with '.vue' file syntax adopted within my company and one of the issues is that though there is linting with eslint for .vue files, js-beatify currently can't format the javascript the same in the .vue files as the rest of our javascript code (so then editing js in vue files is kind of a pain.  

I haven't worked much with the raw code of js-beatify, but if I can figure something out, would you consider accepting a patch for supporting .js-beatify files with the CLI?

**Comment by teazean** [comment]
hi, i have added the .jsbeautifyrc support and changed the cli interface。
now the cli is completely the same as js-beautfiy
